print("Welcome to Mouse of Style, home of the world's largest selection of male and female mouse fashion!")
print("*" * 25)
purchase_item = input("What is the item that you are purchasing today?")
print("What a wonderful choice! I am sure that they will love it.")
purchase_item_price = input(f"What is the price of the {purchase_item} (numbers only, please)?")
purchase_item_quantity = input (f"How many {purchase_item}s are you purchasing today?")
total_price = (float(purchase_item_price)) * (int(purchase_item_quantity))
print(f" You added {purchase_item_quantity} {purchase_item} (s) to your shopping cart!")
print(f"Sutotal: ${total_price}")
print(f"Thank you. Your total today is ${total_price}")